// Shared TypeScript types used across the project

export type FileTag = 'core-logic' | 'boilerplate' | 'config' | 'tests' | 'untagged';

export type FocusArea = 'Architecture' | 'Error Handling' | 'Performance' | 'Security';

export type Difficulty = 'Easy' | 'Medium' | 'Hard';
export type QuestionType = 'mcq' | 'short-answer' | 'descriptive';

export type SessionStatus = 'draft' | 'active' | 'completed';

export type InterviewMode = 'guest' | 'saved';
export type InterviewStyle = 'practice' | 'interview';
export type DifficultyPreset = 'beginner-friendly' | 'balanced' | 'challenging';
export type InterviewTrack = 'repo-viva' | 'systems';
export type SystemTopic =
    | 'Message Queue / Async Processing'
    | 'Graph / Recommendations / Connections'
    | 'Caching / Rate Limiting'
    | 'Notifications / Feed Fanout'
    | 'Search / Indexing'
    | 'Data Modeling / Consistency';

// A file fetched from GitHub with a tag applied by the user
export interface TaggedFile {
    path: string;
    tag: FileTag;
    content?: string; // populated when sending to AI
}

// A single interview question generated by AI
export interface Question {
    type: QuestionType;
    text: string;
    category: FocusArea;
    difficulty: Difficulty; // AI's estimate
    options?: string[];
    correctAnswerIndex?: number;
    explanation: string;
    userDifficulty?: Difficulty; // user's rating after seeing the question
}

// A user's answer + evaluation for one question
export interface Answer {
    questionIndex: number;
    text?: string;
    selectedOptionIndex?: number;
    isCorrect?: boolean;
    score?: number;
    feedback?: string;
    aiAnswer?: string;
    userNote?: string;
}

// Full interview session stored in MongoDB
export interface ISession {
    _id?: string;
    userId?: string;
    repoUrl: string;
    repoOwner: string;
    repoName: string;
    resumeContext?: string;
    taggedFiles: TaggedFile[];
    focusAreas: FocusArea[];
    interviewTrack?: InterviewTrack;
    systemTopics?: SystemTopic[];
    interviewStyle?: InterviewStyle;
    difficultyPreset?: DifficultyPreset;
    questions: Question[];
    answers: Answer[];
    status: SessionStatus;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface GuestSessionState extends Omit<ISession, 'userId'> {
    mode: 'guest';
    lastActiveAt: number;
    expiresAt: number;
}

// GitHub file tree item returned from the API
export interface GitHubFile {
    path: string;
    type: 'blob' | 'tree'; // blob = file, tree = directory
    size?: number;
}

// Shape of the session returned from our API (stringified _id)
export interface SessionSummary {
    _id: string;
    repoUrl: string;
    repoOwner: string;
    repoName: string;
    questionCount: number;
    answerCount: number;
    avgScore: number;
    status: SessionStatus;
    createdAt: string;
}
