// Shared TypeScript types used across the project

export type FileTag = 'core-logic' | 'boilerplate' | 'config' | 'tests' | 'untagged';

export type FocusArea = 'Architecture' | 'Error Handling' | 'Performance' | 'Security';

export type Difficulty = 'Easy' | 'Medium' | 'Hard';

export type SessionStatus = 'draft' | 'active' | 'completed';

// A file fetched from GitHub with a tag applied by the user
export interface TaggedFile {
    path: string;
    tag: FileTag;
    content?: string; // populated when sending to AI
}

// A single interview question generated by AI
export interface Question {
    text: string;
    category: FocusArea;
    difficulty: Difficulty;           // AI's estimate
    userDifficulty?: Difficulty;      // user's rating after seeing the question
}

// A user's answer + AI evaluation for one question
export interface Answer {
    questionIndex: number;
    text: string;            // user's typed answer
    score?: number;          // 1–10 from AI
    feedback?: string;       // AI feedback text
    aiAnswer?: string;       // AI's suggested answer
    userNote?: string;       // user's own annotation
}

// Full interview session stored in MongoDB
export interface ISession {
    _id?: string;
    userId: string;
    repoUrl: string;
    repoOwner: string;
    repoName: string;
    taggedFiles: TaggedFile[];
    focusAreas: FocusArea[];
    questions: Question[];
    answers: Answer[];
    status: SessionStatus;
    createdAt?: Date;
    updatedAt?: Date;
}

// GitHub file tree item returned from the API
export interface GitHubFile {
    path: string;
    type: 'blob' | 'tree'; // blob = file, tree = directory
    size?: number;
}

// Shape of the session returned from our API (stringified _id)
export interface SessionSummary {
    _id: string;
    repoUrl: string;
    repoOwner: string;
    repoName: string;
    questionCount: number;
    answerCount: number;
    avgScore: number;
    status: SessionStatus;
    createdAt: string;
}
